inicioFotos:
  id: "inicio-fotos"
  heroSlides:
    - archivo: "/hero/obelisco-1-recorte.jpg"
      alt: "Vista aérea del Obelisco en Av. 9 de Julio, Buenos Aires"
    - archivo: "/hero/video-av-callao.mp4"
      poster: "/hero/video-av-callao-poster.jpg"
      alt: "Recorrido por Av. Callao, en Recoleta"
    - archivo: "/hero/av-callao.jpg"
      alt: "Av. Callao, en Recoleta"
    - archivo: "/hero/rodriguez-pena-2.jpg"
      alt: "Calle Rodríguez Peña, en Recoleta"
    - archivo: "/hero/teatro-colon.jpg"
      alt: "Teatro Colón, Buenos Aires"
    - archivo: "/hero/congreso.jpg"
      alt: "Palacio del Congreso de la Nación Argentina"
    - archivo: "/hero/pasaje-pizzurno.jpg"
      alt: "Pasaje Pizzurno, Buenos Aires"
    - archivo: "/hero/hospital-aleman.png"
      alt: "Hospital Alemán, en Recoleta"
    - archivo: "/hero/hospital-rivadavia.jpg"
      alt: "Hospital Rivadavia, en Recoleta"
    - archivo: "/hero/alto-palermo.jpg"
      alt: "Shopping Alto Palermo, en Palermo"
    - archivo: "/hero/parque-las-heras.jpg"
      alt: "Parque Las Heras, en Palermo"
    - archivo: "/hero/parque-las-heras-2.jpg"
      alt: "Parque Las Heras, en Palermo"
    - archivo: "/hero/jardin-japones.jpg"
      alt: "Jardín Japonés, en Palermo"
    - archivo: "/hero/floralis-generica.jpg"
      alt: "Floralis Genérica, en Recoleta"
    - archivo: "/hero/rosedal.jpg"
      alt: "El Rosedal de Palermo"
    - archivo: "/hero/obelisco-2.jpg"
      alt: "El Obelisco de Buenos Aires"
    - archivo: "/hero/plaza-lavalle.jpg"
      alt: "Plaza Lavalle, Buenos Aires"
    - archivo: "/hero/ficus-recoleta.jpg"
      alt: "El gran ficus de la Plaza Recoleta"
    - archivo: "/hero/biblioteca-nacional.jpg"
      alt: "Biblioteca Nacional, en Recoleta"
    - archivo: "/hero/embajada-eeuu-argentina.jpg"
      alt: "Embajada de Estados Unidos en Argentina, Palermo"
    - archivo: "/hero/embajada-espana-argentina.png"
      alt: "Embajada de España en Argentina, Recoleta"
    - archivo: "/hero/embajada-gran-bretana-argentina.jpg"
      alt: "Embajada de Gran Bretaña en Argentina, Recoleta"
    - archivo: "/hero/facultad-de-derecho.jpg"
      alt: "Facultad de Derecho de la UBA, en Recoleta"
    - archivo: "/hero/sanatorio-finochietto.jpg"
      alt: "Sanatorio Finochietto"
    - archivo: "/hero/sanatorio-guemes.jpg"
      alt: "Sanatorio Güemes"
    - archivo: "/hero/sanatorio-otamendi.jpg"
      alt: "Sanatorio Otamendi"
