inicioFotos:
  id: "inicio-fotos"
  heroSlides:
    - archivo: "/hero/obelisco-1.jpg"
    - archivo: "/hero/video-av-callao.mp4"
      poster: "/hero/video-av-callao-poster.jpg"
    - archivo: "/hero/av-callao.jpg"
    - archivo: "/hero/rodriguez-pena-2.jpg"
    - archivo: "/hero/teatro-colon.jpg"
    - archivo: "/hero/congreso.jpg"
    - archivo: "/hero/pasaje-pizzurno.jpg"
    - archivo: "/hero/hospital-aleman.png"
    - archivo: "/hero/hospital-rivadavia.jpg"
    - archivo: "/hero/alto-palermo.jpg"
    - archivo: "/hero/parque-las-heras.jpg"
    - archivo: "/hero/parque-las-heras-2.jpg"
    - archivo: "/hero/jardin-japones.jpg"
    - archivo: "/hero/floralis-generica.jpg"
    - archivo: "/hero/rosedal.jpg"
    - archivo: "/hero/obelisco-2.jpg"
    - archivo: "/hero/plaza-lavalle.jpg"
    - archivo: "/hero/ficus-recoleta.jpg"
    - archivo: "/hero/biblioteca-nacional.jpg"
    - archivo: "/hero/embajada-eeuu-argentina.jpg"
    - archivo: "/hero/embajada-espana-argentina.png"
    - archivo: "/hero/embajada-gran-bretana-argentina.jpg"
    - archivo: "/hero/facultad-de-derecho.jpg"
    - archivo: "/hero/sanatorio-finochietto.jpg"
    - archivo: "/hero/sanatorio-guemes.jpg"
    - archivo: "/hero/sanatorio-otamendi.jpg"
