zonasMapa:
  id: "zonas-mapa"
  deptos:
    - "depto-01-av-callao-966"
    - "depto-02-av-callao-930"
    - "depto-03-av-callao-930"
    - "depto-04-av-callao-966"
    - "depto-05-av-callao-966"
    - "depto-06-av-callao-930"
    - "depto-07-av-callao-1234"
    - "depto-08-av-callao-966"
    - "depto-09-av-santa-fe-1955"
    - "depto-10-av-callao-966"
    - "depto-11-av-callao-966"
    - "depto-12-av-callao-930"
    - "depto-13-av-callao-966"
    - "depto-14-av-callao-966"
    - "depto-15-av-callao-930"
    - "depto-16-vicente-lopez-2240"
    - "depto-17-av-callao-966"
    - "depto-18-av-callao-930"
    - "depto-19-av-santa-fe-1886"
    - "depto-20-av-callao-966"
    - "depto-21-av-callao-966"
    - "depto-22-av-callao-930"
    - "depto-23-av-callao-966"
    - "depto-24-av-callao-966"
    - "depto-25-rodriguez-pena-748"
    - "depto-26-viamonte-1815"
    - "depto-27-av-callao-930"
    - "depto-29-paraguay-1937"
    - "depto-30-av-callao-930"
    - "depto-31-av-callao-930"
    - "depto-33-av-callao-930"
    - "depto-34-av-callao-930"
    - "depto-35-av-callao-930"
    - "depto-36-viamonte-1815"
    - "depto-37-av-callao-966"
    - "depto-38-av-callao-930"
    - "depto-39-av-callao-930"
    - "depto-40-av-callao-966"
    - "depto-41-av-callao-966"
    - "depto-46-av-santa-fe-3395"
    - "depto-47-av-callao-966"
    - "depto-48-av-callao-930"
